apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front-end
  name: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - image: shahiddev/front-end:1.0
        imagePullPolicy: IfNotPresent
        name: front-end
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "400Mi"
            cpu: "200m" 
          requests:
            memory: "100Mi"
            cpu: "100m"
          
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-api
  name: back-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - image: shahiddev/backend-api:1.0
        imagePullPolicy: IfNotPresent
        name: backend-api
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "400Mi"
            cpu: "200m" 
          requests:
            memory: "100Mi"
            cpu: "100m"
          
