apiVersion: v1
kind: Service
metadata:
  labels:
    app: front-end
  name: front-end
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: front-end
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-api
  name: backend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: backend-api
  type: ClusterIP
